# docker run -d --rm --name mongo -p 27017:27017 -V mongodbdata:/data/db mongo

version: "4.25.0"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
